Update curl, git in Dockerfile
This fixes the following build issue:
```
ERROR: unsatisfiable constraints:
  curl-7.61.1-r1:
    breaks: world[curl=7.61.1-r0]
  git-2.18.1-r0:
    breaks: world[git=2.18.0-r0]
```