fix: Enable auto-upgrade in beta clusters with a release channel (#682)
* Enable auto-upgrade in beta clusters with a release channel

Without this setting, a cluster with a default node pool will fail when
a release channel is specified. The API responds with:

Error: error creating NodePool: googleapi: Error 400: Auto_upgrade cannot be false when release_channel REGULAR is set., badRequest

This is noted in the documentation, that use of a release channel
requires auto-upgrade and auto-repair to be enabled:

https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels#new-cluster

* Only include comment in beta block, run make build

The previous location I placed the comment meant that it was in place
even in non-beta clusters, so the comment was describing behavior that
wasn't actually in place.

Co-authored-by: Bharath KKB <bharathkrishnakb@gmail.com>