Update go to v1.10.5-r0 in Dockerfile
This fixes the following build issue:
```
ERROR: unsatisfiable constraints:
  go-1.10.5-r0:
    breaks: world[go=1.10.1-r0]
```